version: '3.8'

services:
  murabeiapi:
    build: 
      context: ./backend/murabeiapi
      dockerfile: Dockerfile
    image: murabei_api
    ports:
      - 8000:8000
    volumes:
      - ./backend/murabeiapi:/code
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_ENV=development

  murabeifront:
    build: 
      context: ./frontend/murabei-front
      dockerfile: Dockerfile
    image: murabei_front
    ports:
      - 3000:3000
    volumes:
      - ./frontend/murabei-front:/app
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=development